Feature: TTL cache option in source config
latitude-dev/latitude pull request #301
Opened 2024-04-17 13:41 UTC by csansoon

Added a TTL option in source config. This settings adds en expiration time for query results in the cache. If the cache entry is older than the specified TTL, it is counted as a miss and a fetch will be done.

2024-04-17 13:42 UTC, csansoon commented on apps/server/src/lib/query_service/query_cache.ts
> +    return `${query}__${params.map((param) => param.value).join('__')}`
If we want to eventually make Latitude compatible with Windows, we cannot use `:` as a filename.

2024-04-17 13:43 UTC, andresgutgon commented on apps/server/src/lib/cache_manager/adapters/file_adapter/index.ts
> +        if (Date.now() - stats.mtimeMs > ttl * 1000) {
Did you get inspiration from blog post?

2024-04-17 13:44 UTC, andresgutgon commented on docs/sources/additional-options.mdx
> +  ttl: 3600 # 1 hour of lifetime
I think would be nice if you could define ttl at query level instead of source level

2024-04-17 13:44 UTC, csansoon commented on apps/server/src/lib/cache_manager/adapters/file_adapter/index.ts
> +        if (Date.now() - stats.mtimeMs > ttl * 1000) {
It's really educative!

2024-04-23 16:00 UTC, andresgutgon commented on apps/server/scripts/run_query/index.ts
> +import SOURCE_MANAGER, { QUERIES_DIR } from '../../src/lib/server/sourceManager'
Why uppercase? Is a bit weird. UPPERCASE means constant not singleton

2024-04-23 16:44 UTC, csansoon commented on apps/server/scripts/run_query/index.ts
> +import SOURCE_MANAGER, { QUERIES_DIR } from '../../src/lib/server/sourceManager'
What is a singleton if not a constant instance  🧠

2024-04-24 07:19 UTC, andresgutgon commented on apps/server/scripts/run_query/index.ts
> +import SOURCE_MANAGER, { QUERIES_DIR } from '../../src/lib/server/sourceManager'
Yes but not. A singleton is an instance of a class. This would be a more standard way of representing it. all uppercase are for static values like strings or numbers not for class instances. 

```javascript
const sourceManager = new SourceManager(...)
export sourceManager
```

2024-04-24 07:22 UTC, andresgutgon commented on apps/server/src/lib/query_service/find_or_compute.test.ts
> +    expect(runQuerySpy).toHaveBeenCalledTimes(1) // No additional calls
This is an awesome improvement 👏

2024-04-24 07:25 UTC, andresgutgon commented on packages/cli/src/lib/sync/syncQueries/ensureConnectorInstalled.ts
> +  if (currentRootDir === APP_QUERIES_DIR()) return sourceManager!
weird, you calling a constant?

2024-04-24 07:27 UTC, andresgutgon commented on packages/connectors/base/src/compiledQuery.test.ts
> +    const ranQuerySql = '{@config ttl = 420}'
Nice

2024-04-24 07:32 UTC, andresgutgon commented on packages/connectors/test/CHANGELOG.md
> +# @latitude-data/sqlite-connector
This should not be here no?

2024-04-24 07:53 UTC, csansoon commented on packages/cli/src/lib/sync/syncQueries/ensureConnectorInstalled.ts
> +function SOURCE_MANAGER(): SourceManager {
yeah... reconsidered and fixed :)

2024-04-24 07:57 UTC, andresgutgon submitted a review, later dismissed

2024-04-24 08:03 UTC, csansoon commented on packages/cli/src/lib/sync/syncQueries/ensureConnectorInstalled.ts
> +  if (currentRootDir === APP_QUERIES_DIR()) return sourceManager!
yeah, weird actually. Fixed it moving it to a `get` method in `config`

2024-04-24 08:47 UTC, geclos commented on docs/queries/basics/cache.mdx
> +    This can be configured by setting the `ttl` parameter either in the [source configuration](/sources/additional-config) or [in the query itself](/queries/advanced/config).
You can configure a per-source or per-query ttl with a `ttl` parameter either in the source configuration of the query itself

2024-04-24 08:50 UTC, geclos commented on apps/server/scripts/run_query/index.ts
> +      QueryDisplay.displayCompiledQuery(compiledQuery)
not clear what this method does nor what QueryDisplay is responsible for

2024-04-24 08:50 UTC, geclos commented on apps/server/scripts/run_query/index.ts
> +    })
you are compiling twice?

2024-04-24 08:51 UTC, geclos commented on apps/server/scripts/run_query/index.ts
> +    QueryDisplay.displayError(e as Error)
hmmm i don't understand this api

2024-04-24 08:54 UTC, geclos commented on apps/server/src/lib/query_service/find_or_compute.test.ts
> +    expect(runQuerySpy).toHaveBeenCalledTimes(2) // Called again with different params
very cool improvement in testing 👌🏼

2024-04-24 09:07 UTC, geclos commented on packages/cli/src/lib/sync/syncQueries/ensureConnectorInstalled.ts
> +    await sourceManager.clear(source)
is this really necessary? I would like to avoid adding more dependencies to the cli it's already huge

2024-04-24 09:07 UTC, geclos commented on packages/cli/src/lib/sync/syncQueries/index.ts
> +    if (isSourceFile(destPath)) {
nein, move it [back here](https://github.com/latitude-dev/latitude/pull/301/files#diff-9c8e5af33725b4a2ec7a70dbb065ada75d65e16af66b096a01e62f826c6c7643L103)

2024-04-24 09:16 UTC, geclos approved these changes
awesomest

2024-04-24 11:09 UTC, geclos requested changes
do not merge this, I'm gonna test prerelease versions with it

2024-04-24 15:05 UTC, csansoon commented on packages/connectors/base/src/index.ts
> +  resolvedParams: ResolvedParam[] // Parameters resolved by the connector, in order of appearance
`accessedParams` just contains which of the `params` from the `request` have been accessed.
`resolvedParams` contains the parameters that the query resolved, which are then sent to the database.

Take this query for example:
```sql
SELECT *
FROM users
WHERE birth_year <= {2024 - param('age')}
OR age >= {param('age')}
```

In this case, it would compile to `... birth_year = $1`.
Then, `accessedParams` just contains the following:
```json
{ "age": 30 }
```
because while compilating the query we only have accessed this parameter, and it had that value.

`resolvedParams`  contains the parameters that have been resolved, in order, that get sent to the database along with the query:
```json
[
  { "resolvedAs": "$1", "value": 1994 },
  { "resolvedAs": "$2", "value": 30 }
]
```

2024-04-25 07:41 UTC, csansoon commented on packages/source_manager/src/lib/createConnector/index.ts
> +  [ConnectorType.Test]: 'test-connector',
Because the values in the enum are the accepted values for the `type` field in the source config file. Having them as an enum also makes it easier to reference to those values in other parts of the code, instead of just using strings.

2024-04-25 07:44 UTC, csansoon commented on packages/cli/src/lib/sync/syncQueries/ensureConnectorInstalled.ts
> +    await sourceManager.clear(source)
The source manager is the only one responsible for knowing the package name for each connector and importing them. Should this responsibility be moved somewhere else?

2024-04-25 10:55 UTC, geclos commented on packages/cli/src/lib/sync/syncQueries/ensureConnectorInstalled.ts
> +    await sourceManager.clear(source)
Yeah we'll probably need a shared package in tools at some point, but moving forward for now

2024-04-25 11:11 UTC, geclos submitted a review, later dismissed

2024-04-25 11:17 UTC, merged

2024-04-29 11:56 UTC, geclos commented on apps/server/src/lib/query_service/find_or_compute.ts
> -  return queryPath.slice(queryPath.indexOf(base) + base.length + 1) // query.sql
removed this code caused this regression #348